name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build
        working-directory: frontend
        run: NODE_OPTIONS="--max_old_space_size=4096" npm run build

      - name: Deploy
        working-directory: frontend
        run: |
          git config --global user.name "masroor10"
          git config --global user.email "masroorahmedfcb@gmail.com"
          npx gh-pages -d build -r https://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@github.com/${{ github.repository }}.git
